//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeeng_DB.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        public empresas()
        {
            this.cnpjempresa = new HashSet<cnpjempresa>();
            this.empresaredessociais = new HashSet<empresaredessociais>();
        }
    
        public int idempresa { get; set; }
        public int idsetor { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string urlsite { get; set; }
    
        public virtual ICollection<cnpjempresa> cnpjempresa { get; set; }
        public virtual ICollection<empresaredessociais> empresaredessociais { get; set; }
        public virtual setoresempresa setoresempresa { get; set; }
    }
}
