//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zeeng_DB.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class zeeng_Entities : DbContext
    {
        public zeeng_Entities()
            : base("name=zeeng_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cnpjempresa> cnpjempresa { get; set; }
        public DbSet<empresaredessociais> empresaredessociais { get; set; }
        public DbSet<empresas> empresas { get; set; }
        public DbSet<redessociais> redessociais { get; set; }
        public DbSet<setoresempresa> setoresempresa { get; set; }
    }
}
