//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class anvisa_aliment_regmarcas
    {
        public int idregmarca { get; set; }
        public Nullable<int> idregistro { get; set; }
        public string marca { get; set; }
    
        public virtual anvisa_aliment_registros anvisa_aliment_registros { get; set; }
    }
}
