//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class anvisa_aliment_registros
    {
        public anvisa_aliment_registros()
        {
            this.anvisa_aliment_regmarcas = new HashSet<anvisa_aliment_regmarcas>();
        }
    
        public int idregistro { get; set; }
        public int idcaptura { get; set; }
        public string nomeempresa { get; set; }
        public string cnpj { get; set; }
        public string nomecomercial { get; set; }
        public string cadastro { get; set; }
        public string classeterapeutica { get; set; }
        public string registro { get; set; }
        public string processo { get; set; }
        public string vencimento { get; set; }
        public Nullable<System.DateTime> dtvencimento { get; set; }
        public string detalhe { get; set; }
    
        public virtual anvisa_aliment_capturas anvisa_aliment_capturas { get; set; }
        public virtual ICollection<anvisa_aliment_regmarcas> anvisa_aliment_regmarcas { get; set; }
    }
}
