//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class anvisa_aliment_capturas
    {
        public anvisa_aliment_capturas()
        {
            this.anvisa_aliment_registros = new HashSet<anvisa_aliment_registros>();
        }
    
        public int idcaptura { get; set; }
        public Nullable<System.DateTime> datahorainicio { get; set; }
        public Nullable<System.DateTime> datahorafim { get; set; }
        public string status { get; set; }
        public string descstatus { get; set; }
    
        public virtual ICollection<anvisa_aliment_registros> anvisa_aliment_registros { get; set; }
    }
}
