//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_relatorio_metricas
    {
        public int idclienterelatoriometricas { get; set; }
        public int idclienterelatorio { get; set; }
        public string campo { get; set; }
    
        public virtual cliente_relatorios cliente_relatorios { get; set; }
    }
}
