//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class clientes
    {
        public clientes()
        {
            this.cliente_empresas = new HashSet<cliente_empresas>();
            this.cliente_vertentes = new HashSet<cliente_vertentes>();
            this.usuarios = new HashSet<usuarios>();
            this.cliente_relatorios = new HashSet<cliente_relatorios>();
        }
    
        public int idclientes { get; set; }
        public Nullable<int> idestado { get; set; }
        public string nome { get; set; }
        public string site { get; set; }
        public string endereco { get; set; }
        public string cidade { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string nomecontato { get; set; }
        public string cnpj { get; set; }
        public string email { get; set; }
        public string cep { get; set; }
        public string inscestadual { get; set; }
        public string inscmunicial { get; set; }
        public Nullable<bool> vertodasempresas { get; set; }
        public Nullable<System.DateTime> dtexpiracaolicenca { get; set; }
        public Nullable<int> qtdempresas { get; set; }
        public Nullable<bool> excluido { get; set; }
    
        public virtual ICollection<cliente_empresas> cliente_empresas { get; set; }
        public virtual ICollection<cliente_vertentes> cliente_vertentes { get; set; }
        public virtual estados estados { get; set; }
        public virtual ICollection<usuarios> usuarios { get; set; }
        public virtual ICollection<cliente_relatorios> cliente_relatorios { get; set; }
    }
}
