//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_vertentes
    {
        public int idclientevertente { get; set; }
        public Nullable<int> idcliente { get; set; }
        public Nullable<bool> redessociais { get; set; }
        public Nullable<bool> presencaonline { get; set; }
        public Nullable<bool> noticias { get; set; }
        public Nullable<bool> produtos { get; set; }
        public Nullable<bool> promocoes { get; set; }
    
        public virtual clientes clientes { get; set; }
    }
}
