//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente_relatorios
    {
        public cliente_relatorios()
        {
            this.cliente_relatorio_empresas = new HashSet<cliente_relatorio_empresas>();
            this.cliente_relatorio_metricas = new HashSet<cliente_relatorio_metricas>();
        }
    
        public int idclienterelatorio { get; set; }
        public int idcliente { get; set; }
        public int idusuario { get; set; }
        public string nome { get; set; }
        public DateTime datahora { get; set; }
        public DateTime dataini { get; set; }
        public DateTime datafim { get; set; }
        public bool excluido { get; set; }
    
        public virtual clientes clientes { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual ICollection<cliente_relatorio_empresas> cliente_relatorio_empresas { get; set; }
        public virtual ICollection<cliente_relatorio_metricas> cliente_relatorio_metricas { get; set; }
    }
}
