//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresa_expressoes_noticias
    {
        public int idexpressoesnoticias { get; set; }
        public int idempresa { get; set; }
        public string expressao { get; set; }
        public bool ativo { get; set; }
        public Nullable<System.DateTime> dataultimacaptura { get; set; }
        public long offsetcaptura { get; set; }
        public bool excluido { get; set; }
    
        public virtual empresas empresas { get; set; }
    }
}
