//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class estados
    {
        public estados()
        {
            this.seae_abrang_estado = new HashSet<seae_abrang_estado>();
            this.mapa_registros = new HashSet<mapa_registros>();
            this.promo_estadosabrangencia = new HashSet<promo_estadosabrangencia>();
            this.clientes = new HashSet<clientes>();
            this.municipios = new HashSet<municipios>();
        }
    
        public int idestado { get; set; }
        public string nome { get; set; }
        public string uf { get; set; }
        public Nullable<bool> excluido { get; set; }
    
        public virtual ICollection<seae_abrang_estado> seae_abrang_estado { get; set; }
        public virtual ICollection<mapa_registros> mapa_registros { get; set; }
        public virtual ICollection<promo_estadosabrangencia> promo_estadosabrangencia { get; set; }
        public virtual ICollection<clientes> clientes { get; set; }
        public virtual ICollection<municipios> municipios { get; set; }
    }
}
