//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fb_perfis_stats
    {
        public int idperfilstats { get; set; }
        public long idperfil { get; set; }
        public Nullable<System.DateTime> datahora { get; set; }
        public Nullable<long> qtdlikes { get; set; }
        public Nullable<long> qtdestrelas { get; set; }
        public Nullable<long> qtdavaliacoes { get; set; }
        public Nullable<long> qtdpessoasfalando { get; set; }
    
        public virtual fb_perfis fb_perfis { get; set; }
    }
}
