//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fb_posts
    {
        public fb_posts()
        {
            this.fb_comentarios = new HashSet<fb_comentarios>();
            this.fb_post_termos = new HashSet<fb_post_termos>();
            this.promo_fb_posts = new HashSet<promo_fb_posts>();
        }
    
        public long idpost { get; set; }
        public long idperfil { get; set; }
        public string idfacebook { get; set; }
        public string postagem { get; set; }
        public System.DateTime datahora { get; set; }
        public long compartilhamentos { get; set; }
        public int reacoes { get; set; }
        public long comentarios { get; set; }
        public string tipo { get; set; }
        public string urlimagem { get; set; }
        public string nomeimagem { get; set; }
        public string link { get; set; }
        public Nullable<System.DateTime> datahoraultimocomentario { get; set; }
        public Nullable<bool> termoscapturados { get; set; }
    
        public virtual ICollection<fb_comentarios> fb_comentarios { get; set; }
        public virtual fb_perfis fb_perfis { get; set; }
        public virtual ICollection<fb_post_termos> fb_post_termos { get; set; }
        public virtual ICollection<promo_fb_posts> promo_fb_posts { get; set; }
    }
}
