//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inpi_capturas
    {
        public inpi_capturas()
        {
            this.inpi_registros = new HashSet<inpi_registros>();
        }
    
        public int idcaptura { get; set; }
        public Nullable<System.DateTime> datahorainicio { get; set; }
        public Nullable<System.DateTime> datahorafim { get; set; }
        public string status { get; set; }
        public string descstatus { get; set; }
    
        public virtual ICollection<inpi_registros> inpi_registros { get; set; }
    }
}
