//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inpi_registros
    {
        public inpi_registros()
        {
            this.inpi_registro_peticoes = new HashSet<inpi_registro_peticoes>();
            this.inpi_registro_publicacoes = new HashSet<inpi_registro_publicacoes>();
        }
    
        public int idregistro { get; set; }
        public int idcaptura { get; set; }
        public string numprocesso { get; set; }
        public string empresa { get; set; }
        public string marca { get; set; }
        public string procurador { get; set; }
        public string datadeposito { get; set; }
        public Nullable<System.DateTime> dtdatadeposito { get; set; }
        public string dataconcessao { get; set; }
        public Nullable<System.DateTime> dtdataconcessao { get; set; }
        public string datavigencia { get; set; }
        public Nullable<System.DateTime> dtdatavigencia { get; set; }
        public string situacao { get; set; }
        public string apresentacao { get; set; }
        public string classenice { get; set; }
        public string natureza { get; set; }
        public string especificacao { get; set; }
        public string inicioprazoord { get; set; }
        public string fimprazoord { get; set; }
        public string inicioprazoextra { get; set; }
        public string fimprazoextra { get; set; }
    
        public virtual inpi_capturas inpi_capturas { get; set; }
        public virtual ICollection<inpi_registro_peticoes> inpi_registro_peticoes { get; set; }
        public virtual ICollection<inpi_registro_publicacoes> inpi_registro_publicacoes { get; set; }
    }
}
