//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inpi_registro_publicacoes
    {
        public int idpublicacao { get; set; }
        public int idregistro { get; set; }
        public string rpi { get; set; }
        public string datarpi { get; set; }
        public Nullable<System.DateTime> dtdatarpi { get; set; }
        public string numdespacho { get; set; }
        public string despacho { get; set; }
        public string complemento { get; set; }
    
        public virtual inpi_registros inpi_registros { get; set; }
    }
}
