//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class inpi_registro_peticoes
    {
        public int idpeticoes { get; set; }
        public Nullable<int> idregistro { get; set; }
        public string infospgto { get; set; }
        public string protocolo { get; set; }
        public string data { get; set; }
        public Nullable<System.DateTime> dtdata { get; set; }
        public string numservico { get; set; }
        public string descservico { get; set; }
        public string cliente { get; set; }
        public string delivery { get; set; }
        public string datadelivery { get; set; }
    
        public virtual inpi_registros inpi_registros { get; set; }
    }
}
