//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class insta_comentarios
    {
        public insta_comentarios()
        {
            this.insta_comentario_termos = new HashSet<insta_comentario_termos>();
        }
    
        public int idcomentario { get; set; }
        public int idpost { get; set; }
        public string idinstagram { get; set; }
        public string postagem { get; set; }
        public System.DateTime datahora { get; set; }
        public string idusuario { get; set; }
        public string nomeusuario { get; set; }
        public bool termoscapturados { get; set; }
    
        public virtual insta_posts insta_posts { get; set; }
        public virtual ICollection<insta_comentario_termos> insta_comentario_termos { get; set; }
    }
}
