//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class insta_posts
    {
        public insta_posts()
        {
            this.insta_comentarios = new HashSet<insta_comentarios>();
            this.insta_post_termos = new HashSet<insta_post_termos>();
            this.promo_insta_posts = new HashSet<promo_insta_posts>();
        }
    
        public int idpost { get; set; }
        public int idperfil { get; set; }
        public string idinstagram { get; set; }
        public string postagem { get; set; }
        public System.DateTime datahora { get; set; }
        public int qtdcomentarios { get; set; }
        public int qtdcurtidas { get; set; }
        public string link { get; set; }
        public string urlimagem { get; set; }
        public string nomeimagem { get; set; }
        public string tipo { get; set; }
        public Nullable<System.DateTime> datahoraultimocomentario { get; set; }
        public bool termoscapturados { get; set; }
    
        public virtual ICollection<insta_comentarios> insta_comentarios { get; set; }
        public virtual insta_perfis insta_perfis { get; set; }
        public virtual ICollection<insta_post_termos> insta_post_termos { get; set; }
        public virtual ICollection<promo_insta_posts> promo_insta_posts { get; set; }
    }
}
