//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class insta_comentario_termos
    {
        public int idcomentariotermo { get; set; }
        public Nullable<int> idcomentario { get; set; }
        public string termo { get; set; }
        public Nullable<int> frequencia { get; set; }
    
        public virtual insta_comentarios insta_comentarios { get; set; }
    }
}
