//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public int idlogs { get; set; }
        public int idusuario { get; set; }
        public Nullable<System.DateTime> datahora { get; set; }
        public string url { get; set; }
        public string controle { get; set; }
        public string acao { get; set; }
        public string descricao { get; set; }
        public string nivel { get; set; }
    
        public virtual usuarios usuarios { get; set; }
    }
}
