//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapa_capturas
    {
        public mapa_capturas()
        {
            this.mapa_dadoscaptura = new HashSet<mapa_dadoscaptura>();
            this.mapa_log = new HashSet<mapa_log>();
        }
    
        public int idmapacaptura { get; set; }
        public Nullable<System.DateTime> datahorainicio { get; set; }
        public Nullable<System.DateTime> datahorafim { get; set; }
        public string status { get; set; }
        public string descstatus { get; set; }
    
        public virtual ICollection<mapa_dadoscaptura> mapa_dadoscaptura { get; set; }
        public virtual ICollection<mapa_log> mapa_log { get; set; }
    }
}
