//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapa_statusdadoscaptura
    {
        public int idstatusdadoscaptura { get; set; }
        public Nullable<int> iddadoscaptura { get; set; }
        public Nullable<int> idusuario { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    
        public virtual mapa_dadoscaptura mapa_dadoscaptura { get; set; }
    }
}
