//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapa_registros
    {
        public mapa_registros()
        {
            this.mapa_registro_empresa = new HashSet<mapa_registro_empresa>();
        }
    
        public int idregistro { get; set; }
        public Nullable<int> idestado { get; set; }
        public Nullable<int> idarea { get; set; }
        public Nullable<int> idespecie { get; set; }
        public Nullable<int> idsubespecie { get; set; }
        public Nullable<int> idbase { get; set; }
        public Nullable<int> idcaracteristica { get; set; }
        public Nullable<int> idatributo { get; set; }
        public Nullable<int> idcomplemento { get; set; }
        public Nullable<int> idorigem { get; set; }
        public string cnpj { get; set; }
        public string nomeMarca { get; set; }
        public string nomeProduto { get; set; }
        public Nullable<System.DateTime> dataconcessao { get; set; }
        public string numregistro { get; set; }
        public string modoaplicacao { get; set; }
        public string status { get; set; }
        public Nullable<bool> excluido { get; set; }
    
        public virtual estados estados { get; set; }
        public virtual mapa_areas mapa_areas { get; set; }
        public virtual mapa_atributo mapa_atributo { get; set; }
        public virtual mapa_base mapa_base { get; set; }
        public virtual mapa_caracteristica mapa_caracteristica { get; set; }
        public virtual mapa_complemento mapa_complemento { get; set; }
        public virtual mapa_especies mapa_especies { get; set; }
        public virtual mapa_origens mapa_origens { get; set; }
        public virtual ICollection<mapa_registro_empresa> mapa_registro_empresa { get; set; }
        public virtual mapa_subespecie mapa_subespecie { get; set; }
    }
}
