//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class mapa_log
    {
        public int idmapalog { get; set; }
        public Nullable<int> idmapacaptura { get; set; }
        public Nullable<System.DateTime> datahora { get; set; }
        public string mensagem { get; set; }
        public string descricao { get; set; }
    
        public virtual mapa_capturas mapa_capturas { get; set; }
    }
}
