//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticias
    {
        public noticias()
        {
            this.noticias_empresa = new HashSet<noticias_empresa>();
            this.noticia_imagens = new HashSet<noticia_imagens>();
            this.noticia_termos = new HashSet<noticia_termos>();
            this.noticias_marca = new HashSet<noticias_marca>();
            this.noticias_relacionadas = new HashSet<noticias_relacionadas>();
            this.noticias_relacionadas1 = new HashSet<noticias_relacionadas>();
            this.promo_promonoticias = new HashSet<promo_promonoticias>();
        }
    
        public int idnoticia { get; set; }
        public int idfonte { get; set; }
        public Nullable<int> idnoticia_knewin { get; set; }
        public string titulo { get; set; }
        public string subtitulo { get; set; }
        public string dominio { get; set; }
        public string autor { get; set; }
        public string conteudo { get; set; }
        public string url { get; set; }
        public Nullable<System.DateTime> datapublicacao { get; set; }
        public Nullable<System.DateTime> datacaptura_knewin { get; set; }
        public Nullable<System.DateTime> datacaptura_zeeng { get; set; }
        public string categoria { get; set; }
        public string localidade { get; set; }
        public string linguagem { get; set; }
        public Nullable<bool> excluido { get; set; }
        public Nullable<bool> termoscapturados { get; set; }
    
        public virtual ICollection<noticias_empresa> noticias_empresa { get; set; }
        public virtual fontes_noticias fontes_noticias { get; set; }
        public virtual ICollection<noticia_imagens> noticia_imagens { get; set; }
        public virtual ICollection<noticia_termos> noticia_termos { get; set; }
        public virtual ICollection<noticias_marca> noticias_marca { get; set; }
        public virtual ICollection<noticias_relacionadas> noticias_relacionadas { get; set; }
        public virtual ICollection<noticias_relacionadas> noticias_relacionadas1 { get; set; }
        public virtual ICollection<promo_promonoticias> promo_promonoticias { get; set; }
    }
}
