//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class noticias_relacionadas
    {
        public int idnoticiarelacionadas { get; set; }
        public Nullable<int> idnoticia_princ { get; set; }
        public Nullable<int> idnoticia_rel { get; set; }
    
        public virtual noticias noticias { get; set; }
        public virtual noticias noticias1 { get; set; }
    }
}
