//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class presenca_online_capturas
    {
        public presenca_online_capturas()
        {
            this.presenca_online_palavraspesquisa = new HashSet<presenca_online_palavraspesquisa>();
            this.presenca_online_linkadopor = new HashSet<presenca_online_linkadopor>();
        }
    
        public int idcaptura { get; set; }
        public int idempresa { get; set; }
        public System.DateTime datacaptura { get; set; }
        public Nullable<int> rankbrasil { get; set; }
        public Nullable<int> rankglobal { get; set; }
        public Nullable<int> autoridadedominio { get; set; }
        public Nullable<int> autoridadepagina { get; set; }
        public Nullable<decimal> visitaspesquisa { get; set; }
        public Nullable<decimal> taxarejeicao { get; set; }
        public Nullable<int> pontuacaospam { get; set; }
        public Nullable<int> links { get; set; }
        public Nullable<int> novoslinks { get; set; }
        public Nullable<decimal> paginasvisitadas { get; set; }
        public Nullable<System.TimeSpan> tempovisita { get; set; }
        public Nullable<decimal> audi_feminino { get; set; }
        public Nullable<decimal> audi_masculino { get; set; }
        public Nullable<decimal> audi_semfaculdade { get; set; }
        public Nullable<decimal> audi_algumafaculdade { get; set; }
        public Nullable<decimal> audi_posgraduacao { get; set; }
        public Nullable<decimal> audi_faculdade { get; set; }
        public Nullable<decimal> audi_casa { get; set; }
        public Nullable<decimal> audi_escola { get; set; }
        public Nullable<decimal> audi_trabalho { get; set; }
        public bool excluido { get; set; }
    
        public virtual empresas empresas { get; set; }
        public virtual ICollection<presenca_online_palavraspesquisa> presenca_online_palavraspesquisa { get; set; }
        public virtual ICollection<presenca_online_linkadopor> presenca_online_linkadopor { get; set; }
    }
}
