//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtoredessociais
    {
        public int idprodutoredessociais { get; set; }
        public int idproduto { get; set; }
        public int idredesocial { get; set; }
        public string urlredesocial { get; set; }
    
        public virtual redessociais redessociais { get; set; }
        public virtual produtos produtos { get; set; }
    }
}
