//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class produtos
    {
        public produtos()
        {
            this.produtoredessociais = new HashSet<produtoredessociais>();
        }
    
        public int idproduto { get; set; }
        public Nullable<int> idmarca { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string urlsite { get; set; }
        public Nullable<bool> excluido { get; set; }
        public string imagem { get; set; }
    
        public virtual marcas marcas { get; set; }
        public virtual ICollection<produtoredessociais> produtoredessociais { get; set; }
    }
}
