//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_modalidades
    {
        public promo_modalidades()
        {
            this.promo_promocoes = new HashSet<promo_promocoes>();
        }
    
        public int idpromomodalidade { get; set; }
        public string nome { get; set; }
        public bool excluido { get; set; }
    
        public virtual ICollection<promo_promocoes> promo_promocoes { get; set; }
    }
}
