//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_yt_videos
    {
        public int idpromoytvideos { get; set; }
        public Nullable<int> idvideo { get; set; }
        public Nullable<int> idpromocao { get; set; }
    
        public virtual promo_promocoes promo_promocoes { get; set; }
        public virtual yt_videos yt_videos { get; set; }
    }
}
