//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_tw_posts
    {
        public int idpromotwposts { get; set; }
        public Nullable<int> idpost { get; set; }
        public Nullable<int> idpromocao { get; set; }
    
        public virtual promo_promocoes promo_promocoes { get; set; }
        public virtual tw_posts tw_posts { get; set; }
    }
}
