//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class promo_arquivos
    {
        public int idpromoarquivo { get; set; }
        public Nullable<int> idpromocao { get; set; }
        public string nome { get; set; }
        public string url { get; set; }
        public string conteudo { get; set; }
        public string tipo { get; set; }
        public bool excluido { get; set; }
    
        public virtual promo_promocoes promo_promocoes { get; set; }
    }
}
