//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class redessociais
    {
        public redessociais()
        {
            this.empresaredessociais = new HashSet<empresaredessociais>();
            this.marcaredessociais = new HashSet<marcaredessociais>();
            this.produtoredessociais = new HashSet<produtoredessociais>();
        }
    
        public int idredessociais { get; set; }
        public string nome { get; set; }
        public string nomelogo { get; set; }
    
        public virtual ICollection<empresaredessociais> empresaredessociais { get; set; }
        public virtual ICollection<marcaredessociais> marcaredessociais { get; set; }
        public virtual ICollection<produtoredessociais> produtoredessociais { get; set; }
    }
}
