//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seae_subsetores_proc
    {
        public seae_subsetores_proc()
        {
            this.seae_processo_setor = new HashSet<seae_processo_setor>();
        }
    
        public int idsubsetor { get; set; }
        public Nullable<int> idsetor { get; set; }
        public string codsubsetor { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<seae_processo_setor> seae_processo_setor { get; set; }
        public virtual seae_setores_proc seae_setores_proc { get; set; }
    }
}
