//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seae_processo_setor
    {
        public int idprocessosetor { get; set; }
        public Nullable<int> idprocesso { get; set; }
        public Nullable<int> idsetor { get; set; }
        public Nullable<int> idsubsetor { get; set; }
    
        public virtual seae_processos seae_processos { get; set; }
        public virtual seae_subsetores_proc seae_subsetores_proc { get; set; }
        public virtual seae_setores_proc seae_setores_proc { get; set; }
    }
}
