//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seae_processos
    {
        public seae_processos()
        {
            this.seae_abrang_estado = new HashSet<seae_abrang_estado>();
            this.seae_abrang_municipio = new HashSet<seae_abrang_municipio>();
            this.seae_arquivos_proc = new HashSet<seae_arquivos_proc>();
            this.seae_empresa_processos = new HashSet<seae_empresa_processos>();
            this.seae_mov_situacao = new HashSet<seae_mov_situacao>();
            this.seae_processo_setor = new HashSet<seae_processo_setor>();
            this.seae_processo_solicitantes = new HashSet<seae_processo_solicitantes>();
        }
    
        public int idprocesso { get; set; }
        public string numprocesso { get; set; }
        public Nullable<System.DateTime> dtprocesso { get; set; }
        public Nullable<System.DateTime> dtvigenciaini { get; set; }
        public Nullable<System.DateTime> dtvigenciafim { get; set; }
        public string interessados { get; set; }
        public string premios { get; set; }
        public Nullable<decimal> valortotalpremios { get; set; }
        public string modalidade { get; set; }
        public string formacontemplacao { get; set; }
        public Nullable<bool> abrangencia_nacional { get; set; }
        public Nullable<int> numdocs { get; set; }
        public string nome { get; set; }
        public string resumo { get; set; }
        public string comoparticipar { get; set; }
        public bool atualizarElastic { get; set; }
        public Nullable<bool> excluido { get; set; }
        public Nullable<bool> dadosExtraidos { get; set; }
    
        public virtual ICollection<seae_abrang_estado> seae_abrang_estado { get; set; }
        public virtual ICollection<seae_abrang_municipio> seae_abrang_municipio { get; set; }
        public virtual ICollection<seae_arquivos_proc> seae_arquivos_proc { get; set; }
        public virtual ICollection<seae_empresa_processos> seae_empresa_processos { get; set; }
        public virtual ICollection<seae_mov_situacao> seae_mov_situacao { get; set; }
        public virtual ICollection<seae_processo_setor> seae_processo_setor { get; set; }
        public virtual ICollection<seae_processo_solicitantes> seae_processo_solicitantes { get; set; }
    }
}
