//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seae_setores_proc
    {
        public seae_setores_proc()
        {
            this.seae_processo_setor = new HashSet<seae_processo_setor>();
            this.seae_subsetores_proc = new HashSet<seae_subsetores_proc>();
        }
    
        public int idsetor { get; set; }
        public string codsetor { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<seae_processo_setor> seae_processo_setor { get; set; }
        public virtual ICollection<seae_subsetores_proc> seae_subsetores_proc { get; set; }
    }
}
