//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seae_arquivos_proc
    {
        public int idarquivo { get; set; }
        public Nullable<int> idprocesso { get; set; }
        public string numdoc { get; set; }
        public string coordenacao { get; set; }
        public string situacao { get; set; }
        public string link { get; set; }
        public string nomearquivo { get; set; }
        public string textoarquivo { get; set; }
        public Nullable<bool> excluido { get; set; }
    
        public virtual seae_processos seae_processos { get; set; }
    }
}
