//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class seae_empresa_processos
    {
        public int idempresaprocesso { get; set; }
        public Nullable<int> idprocesso { get; set; }
        public Nullable<int> idempresa { get; set; }
    
        public virtual empresas empresas { get; set; }
        public virtual seae_processos seae_processos { get; set; }
    }
}
