//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tw_perfis_stats
    {
        public int idperfilstats { get; set; }
        public int idperfil { get; set; }
        public System.DateTime datahora { get; set; }
        public int qtdseguidores { get; set; }
        public int qtdseguidos { get; set; }
        public int qtdfavoritado { get; set; }
        public int qtdlistado { get; set; }
        public int qtdtweets { get; set; }
    
        public virtual tw_perfis tw_perfis { get; set; }
    }
}
