//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public usuarios()
        {
            this.logs = new HashSet<logs>();
            this.cliente_relatorios = new HashSet<cliente_relatorios>();
        }
    
        public int idusuario { get; set; }
        public int idcliente { get; set; }
        public string nome { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<bool> excluido { get; set; }
    
        public virtual ICollection<logs> logs { get; set; }
        public virtual clientes clientes { get; set; }
        public virtual ICollection<cliente_relatorios> cliente_relatorios { get; set; }
    }
}
