//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yt_comentarios
    {
        public yt_comentarios()
        {
            this.yt_comentario_termos = new HashSet<yt_comentario_termos>();
            this.yt_comentarios1 = new HashSet<yt_comentarios>();
        }
    
        public int idcomentario { get; set; }
        public string idyoutube { get; set; }
        public int idvideo { get; set; }
        public string postagem { get; set; }
        public int qtdcurtidas { get; set; }
        public System.DateTime datahora { get; set; }
        public Nullable<int> qtdrespostas { get; set; }
        public string nomeusuario { get; set; }
        public string idusuario { get; set; }
        public Nullable<int> idcomentarioresposta { get; set; }
        public bool termoscapturados { get; set; }
        public Nullable<System.DateTime> datahoraultimoreply { get; set; }
    
        public virtual ICollection<yt_comentario_termos> yt_comentario_termos { get; set; }
        public virtual ICollection<yt_comentarios> yt_comentarios1 { get; set; }
        public virtual yt_comentarios yt_comentarios2 { get; set; }
        public virtual yt_videos yt_videos { get; set; }
    }
}
