//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yt_canais_stats
    {
        public int idcanalstats { get; set; }
        public int idcanal { get; set; }
        public System.DateTime datahora { get; set; }
        public int qtdvisualizacoes { get; set; }
        public int qtdseguidores { get; set; }
        public int qtdvideos { get; set; }
    
        public virtual yt_canais yt_canais { get; set; }
    }
}
