//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yt_canais
    {
        public yt_canais()
        {
            this.yt_canais_stats = new HashSet<yt_canais_stats>();
            this.yt_videos = new HashSet<yt_videos>();
        }
    
        public int idcanal { get; set; }
        public Nullable<int> idempresa { get; set; }
        public Nullable<int> idmarca { get; set; }
        public string idyoutube { get; set; }
        public string username { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public string urlimagem { get; set; }
        public string nomeimagem { get; set; }
        public string idlistavideos { get; set; }
        public Nullable<System.DateTime> ultimaatualizacao { get; set; }
        public Nullable<System.DateTime> datahoraultimovideo { get; set; }
    
        public virtual empresas empresas { get; set; }
        public virtual marcas marcas { get; set; }
        public virtual ICollection<yt_canais_stats> yt_canais_stats { get; set; }
        public virtual ICollection<yt_videos> yt_videos { get; set; }
    }
}
