//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yt_video_termos
    {
        public int idvideotermo { get; set; }
        public Nullable<int> idvideo { get; set; }
        public string termo { get; set; }
        public Nullable<int> frequencia { get; set; }
    
        public virtual yt_videos yt_videos { get; set; }
    }
}
