//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class yt_videos
    {
        public yt_videos()
        {
            this.yt_comentarios = new HashSet<yt_comentarios>();
            this.yt_video_termos = new HashSet<yt_video_termos>();
            this.promo_yt_videos = new HashSet<promo_yt_videos>();
        }
    
        public int idvideo { get; set; }
        public int idcanal { get; set; }
        public string idyoutube { get; set; }
        public string titulo { get; set; }
        public string descricao { get; set; }
        public System.DateTime datahora { get; set; }
        public int qtdvisualizacoes { get; set; }
        public int qtdcurtidas { get; set; }
        public int qtddescurtidas { get; set; }
        public int qtdfavoritados { get; set; }
        public int qtdcomentarios { get; set; }
        public string urlimagem { get; set; }
        public string nomeimagem { get; set; }
        public bool termoscapturados { get; set; }
        public Nullable<System.DateTime> datahoraultimocomentario { get; set; }
    
        public virtual yt_canais yt_canais { get; set; }
        public virtual ICollection<yt_comentarios> yt_comentarios { get; set; }
        public virtual ICollection<yt_video_termos> yt_video_termos { get; set; }
        public virtual ICollection<promo_yt_videos> promo_yt_videos { get; set; }
    }
}
