//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZBD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class zeengEntities : DbContext
    {
        public zeengEntities()
            : base("name=zeengEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cnpjempresa> cnpjempresa { get; set; }
        public DbSet<cnpjmarca> cnpjmarca { get; set; }
        public DbSet<empresaredessociais> empresaredessociais { get; set; }
        public DbSet<empresas> empresas { get; set; }
        public DbSet<estados> estados { get; set; }
        public DbSet<mapa_areas> mapa_areas { get; set; }
        public DbSet<mapa_atributo> mapa_atributo { get; set; }
        public DbSet<mapa_base> mapa_base { get; set; }
        public DbSet<mapa_caracteristica> mapa_caracteristica { get; set; }
        public DbSet<mapa_complemento> mapa_complemento { get; set; }
        public DbSet<mapa_especies> mapa_especies { get; set; }
        public DbSet<mapa_origens> mapa_origens { get; set; }
        public DbSet<mapa_subespecie> mapa_subespecie { get; set; }
        public DbSet<marcaredessociais> marcaredessociais { get; set; }
        public DbSet<marcas> marcas { get; set; }
        public DbSet<produtoredessociais> produtoredessociais { get; set; }
        public DbSet<produtos> produtos { get; set; }
        public DbSet<redessociais> redessociais { get; set; }
        public DbSet<setoresempresa> setoresempresa { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<tw_mencoes> tw_mencoes { get; set; }
        public DbSet<tw_perfis> tw_perfis { get; set; }
        public DbSet<tw_perfis_stats> tw_perfis_stats { get; set; }
        public DbSet<tw_posts> tw_posts { get; set; }
        public DbSet<fb_comentarios> fb_comentarios { get; set; }
        public DbSet<insta_perfis> insta_perfis { get; set; }
        public DbSet<insta_perfis_stats> insta_perfis_stats { get; set; }
        public DbSet<yt_canais_stats> yt_canais_stats { get; set; }
        public DbSet<yt_comentarios> yt_comentarios { get; set; }
        public DbSet<fb_comentarios_termos> fb_comentarios_termos { get; set; }
        public DbSet<fb_post_termos> fb_post_termos { get; set; }
        public DbSet<insta_comentarios> insta_comentarios { get; set; }
        public DbSet<insta_posts> insta_posts { get; set; }
        public DbSet<insta_comentario_termos> insta_comentario_termos { get; set; }
        public DbSet<insta_post_termos> insta_post_termos { get; set; }
        public DbSet<tw_post_termos> tw_post_termos { get; set; }
        public DbSet<yt_comentario_termos> yt_comentario_termos { get; set; }
        public DbSet<yt_video_termos> yt_video_termos { get; set; }
        public DbSet<fb_perfis> fb_perfis { get; set; }
        public DbSet<fb_perfis_stats> fb_perfis_stats { get; set; }
        public DbSet<fb_posts> fb_posts { get; set; }
        public DbSet<noticias> noticias { get; set; }
        public DbSet<noticias_empresa> noticias_empresa { get; set; }
        public DbSet<fontes_noticias> fontes_noticias { get; set; }
        public DbSet<noticia_imagens> noticia_imagens { get; set; }
        public DbSet<noticia_termos> noticia_termos { get; set; }
        public DbSet<noticias_marca> noticias_marca { get; set; }
        public DbSet<noticias_relacionadas> noticias_relacionadas { get; set; }
        public DbSet<tw_mencao_termos> tw_mencao_termos { get; set; }
        public DbSet<presenca_online_linkadopor> presenca_online_linkadopor { get; set; }
        public DbSet<presenca_online_palavraspesquisa> presenca_online_palavraspesquisa { get; set; }
        public DbSet<yt_canais> yt_canais { get; set; }
        public DbSet<yt_videos> yt_videos { get; set; }
        public DbSet<presenca_online_capturas> presenca_online_capturas { get; set; }
        public DbSet<seae_setores_proc> seae_setores_proc { get; set; }
        public DbSet<municipios> municipios { get; set; }
        public DbSet<seae_abrang_estado> seae_abrang_estado { get; set; }
        public DbSet<seae_abrang_municipio> seae_abrang_municipio { get; set; }
        public DbSet<seae_arquivos_proc> seae_arquivos_proc { get; set; }
        public DbSet<seae_empresa_processos> seae_empresa_processos { get; set; }
        public DbSet<seae_mov_situacao> seae_mov_situacao { get; set; }
        public DbSet<seae_processo_setor> seae_processo_setor { get; set; }
        public DbSet<seae_processo_solicitantes> seae_processo_solicitantes { get; set; }
        public DbSet<seae_processos> seae_processos { get; set; }
        public DbSet<seae_situacoes> seae_situacoes { get; set; }
        public DbSet<seae_subsetores_proc> seae_subsetores_proc { get; set; }
        public DbSet<mapa_registro_empresa> mapa_registro_empresa { get; set; }
        public DbSet<mapa_registros> mapa_registros { get; set; }
        public DbSet<logs> logs { get; set; }
        public DbSet<promo_arquivos> promo_arquivos { get; set; }
        public DbSet<promo_estadosabrangencia> promo_estadosabrangencia { get; set; }
        public DbSet<promo_fb_posts> promo_fb_posts { get; set; }
        public DbSet<promo_insta_posts> promo_insta_posts { get; set; }
        public DbSet<promo_modalidades> promo_modalidades { get; set; }
        public DbSet<promo_municipiosabrangencia> promo_municipiosabrangencia { get; set; }
        public DbSet<promo_orgaosreguladores> promo_orgaosreguladores { get; set; }
        public DbSet<promo_promocoes> promo_promocoes { get; set; }
        public DbSet<promo_promoempresas> promo_promoempresas { get; set; }
        public DbSet<promo_promonoticias> promo_promonoticias { get; set; }
        public DbSet<promo_regulamentoarquivos> promo_regulamentoarquivos { get; set; }
        public DbSet<promo_tw_posts> promo_tw_posts { get; set; }
        public DbSet<promo_yt_videos> promo_yt_videos { get; set; }
        public DbSet<cliente_empresas> cliente_empresas { get; set; }
        public DbSet<cliente_vertentes> cliente_vertentes { get; set; }
        public DbSet<clientes> clientes { get; set; }
        public DbSet<cliente_relatorios> cliente_relatorios { get; set; }
        public DbSet<cliente_relatorio_empresas> cliente_relatorio_empresas { get; set; }
        public DbSet<cliente_relatorio_metricas> cliente_relatorio_metricas { get; set; }
    
        public virtual ObjectResult<GetTotalMapaPorSemana_Result> GetTotalMapaPorSemana(Nullable<int> idEmpresa, Nullable<System.DateTime> datainicial, Nullable<System.DateTime> datafinal)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("idEmpresa", idEmpresa) :
                new ObjectParameter("idEmpresa", typeof(int));
    
            var datainicialParameter = datainicial.HasValue ?
                new ObjectParameter("datainicial", datainicial) :
                new ObjectParameter("datainicial", typeof(System.DateTime));
    
            var datafinalParameter = datafinal.HasValue ?
                new ObjectParameter("datafinal", datafinal) :
                new ObjectParameter("datafinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetTotalMapaPorSemana_Result>("GetTotalMapaPorSemana", idEmpresaParameter, datainicialParameter, datafinalParameter);
        }
    
        public virtual int GetFacebookCrescimentoFas(Nullable<int> idempresaface, Nullable<System.DateTime> dataInicial, Nullable<System.DateTime> dataFinal)
        {
            var idempresafaceParameter = idempresaface.HasValue ?
                new ObjectParameter("idempresaface", idempresaface) :
                new ObjectParameter("idempresaface", typeof(int));
    
            var dataInicialParameter = dataInicial.HasValue ?
                new ObjectParameter("dataInicial", dataInicial) :
                new ObjectParameter("dataInicial", typeof(System.DateTime));
    
            var dataFinalParameter = dataFinal.HasValue ?
                new ObjectParameter("dataFinal", dataFinal) :
                new ObjectParameter("dataFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetFacebookCrescimentoFas", idempresafaceParameter, dataInicialParameter, dataFinalParameter);
        }
    
        public virtual ObjectResult<GetFacebookInteracoes_Result> GetFacebookInteracoes(Nullable<int> idempresa, Nullable<System.DateTime> dtInicial, Nullable<System.DateTime> dtFinal)
        {
            var idempresaParameter = idempresa.HasValue ?
                new ObjectParameter("idempresa", idempresa) :
                new ObjectParameter("idempresa", typeof(int));
    
            var dtInicialParameter = dtInicial.HasValue ?
                new ObjectParameter("dtInicial", dtInicial) :
                new ObjectParameter("dtInicial", typeof(System.DateTime));
    
            var dtFinalParameter = dtFinal.HasValue ?
                new ObjectParameter("dtFinal", dtFinal) :
                new ObjectParameter("dtFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFacebookInteracoes_Result>("GetFacebookInteracoes", idempresaParameter, dtInicialParameter, dtFinalParameter);
        }
    
        public virtual ObjectResult<GetFacebookInteracoesPorHora_Result> GetFacebookInteracoesPorHora(Nullable<int> idempresa, Nullable<System.DateTime> dtInicial, Nullable<System.DateTime> dtFinal)
        {
            var idempresaParameter = idempresa.HasValue ?
                new ObjectParameter("idempresa", idempresa) :
                new ObjectParameter("idempresa", typeof(int));
    
            var dtInicialParameter = dtInicial.HasValue ?
                new ObjectParameter("dtInicial", dtInicial) :
                new ObjectParameter("dtInicial", typeof(System.DateTime));
    
            var dtFinalParameter = dtFinal.HasValue ?
                new ObjectParameter("dtFinal", dtFinal) :
                new ObjectParameter("dtFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetFacebookInteracoesPorHora_Result>("GetFacebookInteracoesPorHora", idempresaParameter, dtInicialParameter, dtFinalParameter);
        }
    
        public virtual int GetFacebookInteracoesSemana(Nullable<int> idempresa, Nullable<System.DateTime> dtInicial, Nullable<System.DateTime> dtFinal)
        {
            var idempresaParameter = idempresa.HasValue ?
                new ObjectParameter("idempresa", idempresa) :
                new ObjectParameter("idempresa", typeof(int));
    
            var dtInicialParameter = dtInicial.HasValue ?
                new ObjectParameter("dtInicial", dtInicial) :
                new ObjectParameter("dtInicial", typeof(System.DateTime));
    
            var dtFinalParameter = dtFinal.HasValue ?
                new ObjectParameter("dtFinal", dtFinal) :
                new ObjectParameter("dtFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetFacebookInteracoesSemana", idempresaParameter, dtInicialParameter, dtFinalParameter);
        }
    }
}
